### ISSUE TITLE
[Feature Request] Upload hashed email

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycon-etl#30]
## Description

We would like to have a unique key of tables as primary key

## Possible Solution

Use hashed email as the primary key

## Additional context

We don't want the data able to be used to identify a specific person

## Related Issue

https://github.com/pycontw/PyCon-ETL/pull/23

**Comment by uranusjr** [comment]
Is the email promised to be unique? Can an email not purchase multiple tickets on KKTIX?

**Comment by tai271828** [comment]
> Is the email promised to be unique? Can an email not purchase multiple tickets on KKTIX?

1. Yes, it is unique.
2. `Can an email not purchase multiple tickets on KKTIX?` No. By default, the email associates the owner's kktix account, who consumes the ticket.
2-1. Some special tickets are sold in a batch and brought by one person. In this case, the email of the ticket associates customized information like t-shirt size and day-1/day-2/day-3 check-in status. Thus, the information of email is still unique.

**Comment by tai271828** [comment]
Please notice the feature is implemented in this pull request https://github.com/pycontw/PyCon-ETL/pull/23 .
