### ISSUE TITLE
[Feature Request] Strip privacy columns when uploading ticket data

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycon-etl#39]
## Description
When working on https://github.com/pycontw/PyCon-ETL/issues/5 , we have a tool to upload ticket data like https://github.com/pycontw/PyCon-ETL/pull/23 . The raw data is stripped privacy-related columns manually prior to uploading. It will be great if we could have fool-proof, or something automatically stripping the columns that we don't want to upload, when uploading.

## Possible Solution
Check black list of columns and remove them from data frames.

The current candidates of column to remove in my mind:
```
(kktix) id
order number
checkin code
qr code serial no
nickname
Contact Name
contact mobile
```

Please note we keep contact emails and upload their hashed version. Ref to the context: https://github.com/pycontw/PyCon-ETL/issues/30

**Comment by grimmer0125** [comment]
@tai271828 https://pydantic-docs.helpmanual.io/ may be a good tool to handle this?

**Comment by tai271828** [comment]
> @tai271828 https://pydantic-docs.helpmanual.io/ may be a good tool to handle this?

@grimmer0125  thank you for the tip. The issue was resolved earlier but I forgot to update the issue status. The tip may be used for future improvement.
