### ISSUE TITLE
[Bug Report] Fail to install packages on Mac M1

### ISSUE THREAD

**Issue by grimmer0125** [pycontw/pycon-etl#46]
## Description
As title.

## version
Latest master

## Steps to Reproduce

will fill more details later.

Failure cases 
- 3.9.2:  
    - `numpy` (used by `pyarrow`, `pandas`)
    -  Installing cryptography (3.4.5): Failed
    - Installing flask-oauthlib (0.9.5) EnvCommandError
- 3.8: not test yet. 
- 3.7.10: `markupsafe` (2.0.1)

**Comment by uranusjr** [comment]
Try re-building the lock file (`poetry lock` or something). Numpy is providing universal2 builds for 1.21.0 and later, but the current lock file requires 1.20.1 which is too old.

**Comment by grimmer0125** [comment]
Thanks. It's good news and will try it later.

**Comment by grimmer0125** [comment]
@uranusjr it works and thank you again.

**Comment by grimmer0125** [comment]
Some warning, and note it first: 
```
/Users/grimmer/git/pycon-etl/.venv/lib/python3.9/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
```
